### ISSUE TITLE
discrepancy between real time analysis and post run analysis

### ISSUE THREAD

**Issue by jagos01** [mriglobal/PanGIA_GUI#1]
Hello,
I recently installed PanGIA_GUI and tested it on a small subset of data.  I obtained different results when running real time analysis and post run analysis.  Real time analysis indicated only plasmodium sp. in my sample while post run analysis correctly identifies my sample.  What database does the real time analysis use?  Is there a way to specify what databases to use?
Thanks,
Scott

**Comment by mriglobal** [comment]
Hi Scott,
Yes we found out recently that the SAM input method with certain indices are not working correctly. We're planning on pushing a temporary fix that concatenates fastqs instead of the SAMs. However, we're not going to get around to this fix until first week of January. We'll come back here and let you know when it's been pushed.

**Comment by jagos01** [comment]
Thanks.  Looking forward to the update.

**Comment by mriglobal** [comment]
Hi Scott,
So we got to the bottom of what's happening. It turns out everything works fine, but we deployed databases without requisite files. To concatenate the SAM files during each step of the real time loop it needs a fasta index file (.fai) for each database fasta and it can't create it a la carte because the actual fasta files are just empty filename interfaces, ie. they don't contain data. We've redeployed the database located at http://pangia1.0.s3.amazonaws.com/pangia_database.tar.gz to include those .fai files. If you re-download the database and extract it again using the directions in the README you should be good to go. Please let me know if that works, and if it does, I'll close this.

**Comment by jagos01** [comment]
Real time analysis works great with the new database. Thanks.
